service: ${env:PROJECT_NAME}
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

  stage: ${env:STAGE}
  region: ${env:REGION}

resources:
  Resources:
    vpc0:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 192.168.0.0/24
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}-vpc0
          - Key: project
            Value: ${self:service}
    cluster0:
      Type: AWS::ECS::Cluster
      Properties:
        CapacityProviders: [FARGATE]
        ClusterName: ${self:service}-${self:provider.stage}-cluster0
        ClusterSettings:
          - Name: containerInsights
            Value: enabled
        Tags:
          - Key: project
            Value: ${self:service}
    repo0:
      Type: AWS::ECR::Repository
      Properties:
        ImageScanningConfiguration: { scanOnPush: true }
        ImageTagMutability: IMMUTABLE
        RepositoryName: ${self:service}-${self:provider.stage}
        # RepositoryPolicyText: # Needed for non-root push image
        Tags:
          - Key: project
            Value: ${self:service}
    taskDefinition0:
      Type: AWS::ECS::TaskDefinition
      Properties:
        ContainerDefinitions:
          - Image: ${env:ECR_IMG_URI}
            Name: container0
            PortMappings:
              -  ContainerPort: 5000
                 HostPort: 5000
                 Protocol: TCP
        Cpu: 256
        # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html#create-task-execution-role
        ExecutionRoleArn: arn:aws:iam::${env:ACCOUNT_ID}:role/ecsTaskExecutionRole
        Memory: 512
        NetworkMode: awsvpc
        RequiresCompatibilities: [FARGATE]
        Tags:
          - Key: project
            Value: ${self:service}
